---
- name: Demonstrate use of ansible module
  hosts: centos
  gather_facts: false
  tasks:
    - name: Check of python is installed in managed nodes
      ansible.builtin.ping:
      tags:
        - never
        - ping
    - name: Reboot all managed nodes in centos group
      ansible.builtin.reboot:
      tags:
        - never
- name: Install packages
  hosts: centos
  gather_facts: false
  tasks:
    - name: Install git and java
      ansible.builtin.dnf:
        name:
          - git
          - java-17-openjdk
        state: present
      tags: 
        - never
